# @package _group_
_target_: pl_igscmaes.data.dataset.RealPsFittingDataset
name: # DB Name 
bperp_dir: # BPerp Dir in float bytes 
bperp_ext: '.bperp'
ifg_dir: # IFG Dir   in complex bytes
ifg_ext: '.diff.orb.statm_cor.natm.filt'
filt_dir: # Filtered IFG Dir in complex bytes
filt_ext: '.diff.orb.statm_cor.natm.filt'
coh_dir: # Coherence Dir  in float bytes
coh_ext: '.diff.orb.statm_cor.natm.filt.coh'
rslc_dir: # RSLC Dir in shortcomplex bytes
rslc_ext: '.rmli'
ref_mr_path: # Reference motion rate in float bytes
ref_he_path: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/fit_hr/hgt_fit_m'
width: 1500 
height: 1500 
conv1: # conv_def
conv2: # conv_top
ps_coords_path: # PS locations 
